--#Regions
insert into region (id, name_en, name_ru, name_uz,name_kr) values (1, 'Republic of Karakalpakstan', 'Республика Каракалпакстан', 'Qoraqalpog`iston Respublikasi','Қорақалпоғистон Республикаси');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (2, 'Andijan region', 'Андижанская область', 'Andijon viloyati','Андижон вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (3, 'Bukhara region', 'Бухарская область', 'Buxoro viloyati','Бухоро вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (4, 'Jizzakh region', 'Джизакская область', 'Jizzax viloyati','Жиззах вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (5, 'Kashkadarya region', 'Кашкадарьинская область', 'Qashqadaryo viloyati','Қашқадарё вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (6, 'Navoi region', 'Навоийская область', 'Navoiy viloyati','Навоий вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (7, 'Namangan region', 'Наманганская область', 'Namangan viloyati','Наманган вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (8, 'Samarqand region', 'Самаркандская область', 'Samarqand viloyati','Самарқанд вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (9, 'Surxondaryo region', 'Сурхандарьинская область', 'Surxondaryo viloyati','Сурхондарё вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (10, 'Sirdaryo region', 'Сырдарьинская область', 'Sirdaryo viloyati','Сирдарё вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (11, 'Tashkent region', 'Ташкентская область', 'Toshkent viloyati','Тошкент вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (12, 'Fergana region', 'Ферганская область', 'Farg`ona viloyati','Фарғона вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (13, 'Xorazm region', 'Хорезмская область', 'Xorazm viloyati','Хоразм вилояти');
insert into region (id, name_en, name_ru, name_uz,name_kr) values (14, 'Tashkent city', 'город Ташкент', 'Toshkent shahri','Тошкент шахри');
--#Districts
--#Republic of Karakalpakstan
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Amudaryo district', 'Амударьинский район', 'Amudaryo tumani','Амударё тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Beruniy district', 'Берунийский район', 'Beruniy tumani','Беруний тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Kegeyli district', 'Кегейлийский район', 'Kegeyli tumani','Кегейли тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Qonlikul district', 'Канлыкульский район', 'Qonliko‘l tumani','Қонликўл тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Qorao‘zak district', 'Караузякский район', 'Qorao‘zak tumani','Қораўзак тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Qo‘ng‘irot district', 'Кунградский район', 'Qo‘ng‘irot tumani','Қўнғирот тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Mo‘ynoq district', 'Муйнакский район', 'Mo‘ynoq tumani','Мўйноқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Nukus district', 'Нукусский район', 'Nukus tumani','Нукус тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Nukus city', 'город Нукус', 'Nukus shahri','Нукус шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Taxtakupir district', 'Тахтакупырский район', 'Taxtako‘pir tumani','Тахтакўпир тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Turtkul district', 'Турткульский район', 'To‘rtko‘l tumani','Тўрткўл тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Xujayli district', 'Ходжейлийский район', 'Xo‘jayli tumani','Хўжайли тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Chimboy district', 'Чимбайский район', 'Chimboy tumani','Чимбой тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Shumanay district', 'Шуманайский район', 'Shumanay tumani','Шуманай тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Ellikqala district', 'Элликкалинский район', 'Ellikqala tumani','Элликқала тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (1, 'Taxiatosh city', 'город Тахиатош', 'Taxiatosh shahri','Тахиатош шахри');

--#Andijan region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Andijan city', 'город Андижан', 'Andijon shahri','Андижон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Andijan district', 'Андижанский район', 'Andijon tumani','Андижон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Asaka district', 'Асакинский район', 'Asaka tumani','Асака тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Asaka city', 'город Асака', 'Asaka shahri','Асака шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Balikchi district', 'Балыкчинский район', 'Baliqchi tumani','Балиқчи тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Buloqboshi district', 'Булакбашинский район', 'Buloqboshi tumani','Булоқбоши тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Bo`z district', 'Бозский район', 'Bo`z tumani','Бўз тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Jalaquduq district', 'Джалалкудукский район', 'Jalaquduq tumani','Жалақудуқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Izboskan district', 'Избасканский район', 'Izboskan tumani','Избоскан тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Qorasuv city', 'Қорасув район', 'Qorasuv shahri','Қорасув шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Qurgantepa district', 'Кургантепинский район', 'Qo`rg`ontepa tumani','Қўрғонтепа тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Marhamat district', 'Мархаматский район', 'Marhamat tumani','Марҳамат тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Oltinkul district', 'Алтынкульский район', 'Oltink`ol tumani','Олтинкъол тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Pakhtaabad district', 'Пахтаабадский район', 'Paxtaobod tumani','Пахтаобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Ulugnor district', 'Улугнорский район', 'Ulug`nor tumani','Улуғнор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Xonabod district', ' Ханабадский район', 'Xonabod tumani','Хонабод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Xujaabad district', 'Ходжаабадский район', 'Xo`jaobod tumani','Хўжаобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (2, 'Shakhrixon district', 'Шахриханский район', 'Shahrixon tumani','Шаҳрихон тумани');
--#Bukhara region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Bukhara city', 'город Бухара', 'Buxoro shahri','Бухоро шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Bukhara district', 'Бухарский район', 'Buxoro tumani','Бухоро тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Vobkent district', 'Вабкентский район', 'Vobkent tumani','Вобкент тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Gijduvan district', 'Гиждуванский район', 'G`ijduvon tumani','Ғиждувон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Jondor district', 'Жондорский район', 'Jondor tumani','Жондор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Kogon district', 'Каганский район', 'Kogon tumani','Когон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Kogon city', 'город Каган', 'Kogon shahri','Когон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Qorako`l district', 'Каракульский район', 'Qorako`l tumani','Қоракўл тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Qorovulbozor district', 'Караулбазарский район', 'Qorovulbozor tumani','Қоровулбозор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Olot district', 'Алатский район', 'Olot tumani','Олот тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Peshku district', 'Пешкунский район', 'Peshku tumani','Пешку тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Romitan district', 'Ромитанский район', 'Romitan tumani','Ромитан тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (3, 'Shofirkon district', 'Шафирканский район', 'Shofirkon tumani','Шофиркон тумани');
--#Jizzakh region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Arnasay district', 'Арнасайский район', 'Arnasoy tumani','Арнасой тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Bakhmal district', 'Бахмальский район', 'Baxmal tumani','Бахмал тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Gallaorol district', 'Галляаральский район', 'G`allaorol tumani','Ғаллаорол тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Dustlik district', 'Дустликский район', 'Do`stlik tumani','Дўстлик тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Sharof-Rashidov district', 'Шараф-Рашидовский район', 'Sharof-Rashidov tumani','Шароф-Рашидов тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Jizzax city', 'город Джизак ', 'Jizzax shahri','Жиззах шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Zarbdar district', 'Зарбдарский район', 'Zarbdor tumani','Зарбдор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Zaamin district', 'Зааминский район', 'Zomin tumani','Зомин тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Mirzachul district', 'Мирзачульский район', 'Mirzacho`l tumani','Мирзачўл тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Pakhtakor district', 'Пахтакорский район', 'Paxtakor tumani','Пахтакор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Forish district', 'Фаришский район', 'Forish tumani','Фориш тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (4, 'Yangiabad district', 'Янгиабадский район', 'Yangiobod tumani','Янгиобод тумани');
--#Kashkadarya region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Guzar tumani', 'Гузарский район', 'G‘uzor tumani','Ғузор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Dehkanabad district', 'Дехканабадский район', 'Dehqonobod tumani','Деҳқонобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Kamashi district', 'Камашинский район', 'Qamashi tumani','Қамаши тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Karshi district', 'Каршинский район', 'Qarshi tumani','Қарши тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Karshi city', 'город Карши', 'Qarshi shahri','Қарши шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Kasby district', 'Касбийский район', 'Kasbi tumani','Касби тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Kitob district', 'Китабский район', 'Kitob tumani','Китоб тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Koson district', 'Касанский район', 'Koson tumani','Косон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Myrishkor district', 'Миришкорский район', 'Mirishkor tumani','Миришкор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Muborak district', 'Мубарекский район', 'Muborak tumani','Муборак тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Nishon district', 'Нишанский район', 'Nishon tumani','Нишон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Chirakchi district', 'Чиракчинский район', 'Chiroqchi tumani','Чироқчи тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Shakhrisabz district', 'Шахрисабзский район', 'Shahrisabz tumani','Шаҳрисабз тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (5, 'Yakkabog district', 'Яккабагский район', 'Yakkabog` tumani','Яккабоғ тумани');
--#Navoi region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Zarafshon city', 'город Зарафшон', 'Zarafshon shahri','Зарафшон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Karmana district', 'Карманинский район', 'Karmana tumani','Кармана тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Kyzyltepa district', 'Кызылтепинский район', 'Qiziltepa tumani','Қизилтепа тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Kanimekh district', 'Канимехский район', 'Konimex tumani','Конимех тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Navbakhor district', 'Навбахорский район', 'Navbahor tumani','Навбаҳор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Navoiy city', 'город Навои', 'Navoiy shahri','Навоий шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Nurata district', 'Нуратинский район', 'Nurota tumani','Нурота тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Tamdy district', 'Тамдынский район', 'Tomdi tumani','Томди тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Uchkuduk district', 'Учкудукский район', 'Uchquduq tumani','Учқудуқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (6, 'Khatyrchi district', 'Хатырчинский район', 'Xatirchi tumani','Хатирчи тумани');
--#Namangan region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Kasansay district', 'Касансайский район', 'Kosonsoy tumani','Косонсой тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Mingbulak district', 'Мингбулакский район', 'Mingbuloq tumani','Мингбулоқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Namangan district', 'Наманганский район', 'Namangan tumani','Наманган тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Namangan city', 'город Наманган', 'Namangan shahri','Наманган шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Naryn district', 'Нарынский район', 'Norin tumani','Норин тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Pap district', 'Папский район', 'Pop tumani','Поп тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Turakurgan district', 'Туракурганский район', 'To`raqo`rg`on tumani','Тўрақўрғон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Uychi district', 'Уйчинский район', 'Uychi tumani','Уйчи тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Uchkurgan district', 'Учкурганский район', 'Uchqo`rg`on tumani','Учқўрғон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Chartak district', 'Чартакский район', 'Chortoq tumani','Чортоқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Chust district', 'Чустский район', 'Chust tumani','Чуст тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (7, 'Yangikurgan district', 'Янгикурганский район', 'Yangiqo`rg`on tumani','Янгиқўрғон тумани');
--#Samarqand region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Bulungur district', 'Булунгурский район', 'Bulung`ur tumani','Булунғур тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Jomboy district', 'Джамбайский район', 'Jomboy tumani','Жомбой тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Ishtikhon district', 'Иштыханский район', 'Ishtixon tumani','Иштихон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Kattakurgan district', 'Каттакурганский район', 'Kattaqo`r`on tumani','Каттақўръон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Kattakurgan city', 'Каттакурганский город', 'Kattaqo`r`on shahri','Каттақўръон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Koshrabot district', 'Кошрабадский район', 'Qo`shrabot tumani','Қўшработ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Narpay district', 'Нарпайский район', 'Narpay tumani','Нарпай тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Nurobod district', 'Нурабадский район', 'Nurobod tumani','Нуробод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Oqdarya district', 'Акдарьинский район', 'Oqdaryo tumani','Оқдарё тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Payariq district', 'Пайарыкский район', 'Payariq tumani','Пайариқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Pastdargom district', 'Пастдаргомский район', 'Pastdarg`om tumani','Пастдарғом тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Pakhtachi district', 'Пахтачийский район', 'Paxtachi tumani','Пахтачи тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Samarqand district', 'Самаркандский район', 'Samarqand tumani','Самарқанд тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Samarqand city', 'город Самарканд', 'Samarqand shahri','Самарқанд шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Toyloq district', 'Тайлакский район', 'Toyloq tumani','Тойлоқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (8, 'Urgut district', 'Ургутский район', 'Urgut tumani','Ургут тумани');
--#Surxondaryo region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Angor district', 'Ангорский район', 'Angor tumani','Ангор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Bandixon district', 'Бандиханский район', 'Bandixon tumani','Бандихон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Boysun district', 'Байсунский район', 'Boysun tumani','Бойсун тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Denov district', 'Денауский район', 'Denov tumani','Денов тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Jarkurghon district', 'Джаркурганский район', 'Jarqo`rg`on tumani','Жарқўрғон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Kizirik district', 'Кизирикский район', 'Qiziriq tumani','Қизириқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Kumkurghon district', 'Кумкурганский район', 'Qumqo`rg`on tumani','Қумқўрғон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Muzrabot district', 'Музрабадский район', 'Muzrabot tumani','Музработ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Oltinsoy district', 'Алтынсайский район', 'Oltinsoy tumani','Олтинсой тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Sariosiyo district', 'Сариасийский район', 'Sariosiyo tumani','Сариосиё тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Termiz district', 'Термезский район', 'Termiz tumani','Термиз тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Termiz city', 'город Термез', 'Termiz shahri','Термиз шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Uzun district', 'Узунский район', 'Uzun tumani','Узун тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Sherobod district', 'Шерабадский район', 'Sherobod tumani','Шеробод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (9, 'Shurchi district', 'Шурчинский район', 'Sho`rchi tumani','Шўрчи тумани');
--#Sirdaryo region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Bayaut district', 'Баяутский район', 'Boyovut tumani','Боёвут тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Gulistan district', 'Гулистанский район', 'Guliston tumani','Гулистон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Gulistan city', 'город Гулистан', 'Guliston shahri','Гулистон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Mirzaabad district', 'Мирзаабадский район', 'Mirzaobod tumani','Мирзаобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Akaltyn district', 'Акалтынский район', 'Akaltyn tumani','Акалтйн тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Saikhunabad district', 'Сайхунабадский район', 'Sayhunobod tumani','Сайҳунобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Sardoba district', 'Сардобский район', 'Sardoba tumani','Сардоба тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Sirdaryo district', 'Сырдарьинский район', 'Sirdaryo tumani','Сирдарё тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Khavast district', 'Хавастский район', 'Xovos tumani','Ховос тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Shirin city', 'город Ширин', 'Shirin shahri','Ширин шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (10, 'Yangiyer city', 'город Янгиер', 'Yangiyer shahri','Янгиер шахри');
--#Tashkent region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Angren city', ' город Ангрен', 'Angren shahri','Ангрен шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Bekabad district', 'Бекабадский район', 'Bekobod tumani','Бекобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Bekabad city', 'город Бекабад', 'Bekobod shahri','Бекобод шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Buka district', 'Букинский район', 'Bo`ka tumani','Бўка тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Bostanliq district', 'Бостанлыкский район', 'Bo`stonliq tumani','Бўстонлиқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Zangiata district', 'Зангиатинский район', 'Zangiota tumani','Зангиота тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Qibray district', 'Кибрайский район', 'Qibray tumani','Қибрай тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Quyi Chirchik district', 'Куйичирчикский район', 'Quyi Chirchiq tumani','Қуйи Чирчиқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Oqqurgan district', 'Аккурганский район', 'Oqqo`rg`on tumani','Оққўрғон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Olmaliq city', ' город Алмалык', 'Olmaliq shahri','Олмалиқ шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Okhangaron district', 'Ахангаранский район', 'Oxangaron tumani','Охангарон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Okhangaron city', 'город Ахангаран', 'Oxangaron shahri','Охангарон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Parkent district', 'Паркентский район', 'Parkent tumani','Паркент тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Piskent district', 'Пскентский район', 'Piskent tumani','Пискент тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Urta Chirchik district', 'Уртачирчикский район', 'O`rta Chirchiq tumani','Ўрта Чирчиқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Chinaz district', 'Чиназский район', 'Chinoz tumani','Чиноз тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Chirchik city', 'город Чирчик', 'Chirchiq shahri','Чирчиқ шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Yukori Chirchik district', 'Юкоричирчикский район', 'Yuqori Chirchiq tumani','Юқори Чирчиқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Yangiyul district', 'Янгиюльский район', 'Yangiyo`l tumani','Янгийўл тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Yangiyul city', 'город Янгиюль', 'Yangiyo`l shahri','Янгийўл шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (11, 'Tashkent district', 'Ташкентский район', 'Toshkent tumani','Тошкент тумани');
--#Fergana region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Beshariq district', 'Бешарыкский район', 'Beshariq tumani','Бешариқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Baghdad district', 'Багдадский район', 'Bog`dod tumani','Боғдод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Buvayda district', 'Бувайдинский район', 'Buvayda tumani','Бувайда тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Dangara district', 'Дангаринский район', 'Dang`ara tumani','Данғара тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Yozyovon district', 'Язъяванский район', 'Yozyovon tumani','Ёзёвон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Quva district', 'Кувинский район', 'Quva tumani','Қува тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Quvasay city', 'город Кувасай', 'Quvasoy shahri','Қувасой шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Kokand city', 'город Коканд', 'Qo`qon shahri','Қўқон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Qo`shtepa district', 'Куштепинский район', 'Qo`shtepa tumani','Қўштепа тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Margilon city', 'город Маргилан', 'Marg`ilon shahri','Марғилон шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Altyariq district', 'Алтыарыкский район', 'Oltiariq tumani','Олтиариқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Rishton district', 'Риштанский район', 'Rishton tumani','Риштон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Sokh district', 'Сохский район', 'So`x tumani','Сўх тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Tashlaq district', 'Ташлакский район', 'Toshloq tumani','Тошлоқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Uchkuprik district', 'Учкуприкский район', 'Uchko`prik tumani','Учкўприк тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Uzbekistans district', 'Узбекистанский район', 'O`zbekistons tumani','Ўзбекистон тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Fergana district', 'Ферганский район', 'Farg`ona tumani','Фарғона тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Fergana city', 'город Фергана', 'Farg`ona shahri','Фарғона шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (12, 'Furqat district', 'Фуркатский район', 'Furqat tumani','Фурқат тумани');
--#Xorazm region
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Bog‘ot district', 'Багатский район', '	Bog‘ot tumani','Боғот тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Do`stlik city', 'город Дустлик', 'Do`stlik shahri','Дўстлик шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Gurlen district', 'Гурленский район', 'Gurlan tumani','Гурлан тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Qo‘shko‘pir district', 'Кошкупырский район', 'Qo‘shko‘pir tumani','Қўшкўпир тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Urganch district', 'Ургенчский район', 'Urganch tumani','Урганч тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Urganch city', 'город Ургенч', 'Urganch shahri','Урганч шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Khiva district', 'Хивинский район', 'Xiva tumani','Хива тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Khiva city', 'город Хива', 'Xiva shahri','Хива шахри');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Hazorasp district', 'Хазараспский район', 'Hazorasp tumani','Ҳазорасп тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Xonqa district', 'Ханкинский район', 'Xonqa tumani','Хонқа тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Shovot district', 'Шаватский район', 'Shovot tumani','Шовот тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Yangiariq district', 'Янгиарыкский район', 'Yangiariq tumani','Янгиариқ тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (13, 'Yangibozor district', 'Янгибазарский район', 'Yangibozor tumani','Янгибозор тумани');
--#Tashkent city
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Bektemir district', 'Бектемирский район', 'Bektemir tumani','Бектемир тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Mirzo Ulugbek district', 'Мирзо-Улугбекский район', 'Mirzo Ulug`bek tumani','Мирзо Улуғбек тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Mirobod district', 'Мирабадский район', 'Mirobod tumani','Миробод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Olmazor district', 'Алмазарский район', 'Olmazor tumani','Олмазор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Sergeli district', 'Сергелийский район', 'Sirg`ali tumani','Сирғали тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Uchtepa district', 'Учтепинский район', 'Uchtepa tumani','Учтепа тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Yashnobod district', 'Яшнободский район', 'Yashnobod tumani','Яшнобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Chilonzor district', 'Чиланзарский район', 'Chilonzor tumani','Чилонзор тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Shaykhantahur district', 'Шайхантахурский район', 'Shayxontohur tumani','Шайхонтоҳур тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Yunusobod district', 'Юнусабадский район', 'Yunusobod tumani','Юнусобод тумани');
insert into district (region_id, name_en, name_ru, name_uz,name_kr) values (14, 'Yakkasaray district', 'Яккасарайский район', 'Yakkasaroy tumani','Яккасарой тумани');
